---
- name: Deploy SSH private key
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: /home/ec2-user/.ssh
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0700'

    - name: Accept new host keys and add to known_hosts
      ansible.builtin.shell:
        cmd: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"
      changed_when: false  # This task is always considered stable
      connection: local  # Run this task on the control node, not the target

      # Now, gather facts which requires an SSH connection
    - name: Gather facts
      ansible.builtin.setup:

    # Finally, distribute and authorize the SSH key
    - name: Add your public key to the ec2-user's authorized_keys
      ansible.builtin.authorized_key:
        user: "{{ ssh_username }}"  # Comes from the credential
        state: present
        key: "{{ public_ssh_key }}"  # Comes from the credential
      delegate_to: "{{ inventory_hostname }}"

    - name: Install some tools I like to user
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - bind-utils
        - telnet
        - tree

    - name: Disable EPEL repository
      ansible.builtin.dnf:
        name: epel
        state: disabled
      ignore_errors: yes  # Proceeds if EPEL repo is not present

    - name: Register systems
      include_role: 
        name: redhat.rhel_system_roles.rhc
      vars:
        rhc_auth:
          login:
            username: "bforrest@redhat.com"
            password: "EBf2009$#"
          