---
- name: Create RHEL 8 EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws
    - ansible.builtin

  vars_files: 
    - credentials.yml
  vars:
    #Your region
    #region: us-east-1
    region: "{{ which_region }}" 
    #sgname: AA-Lab
    #sgname: "{{ which_security_group }}" 
  tasks:

    - name: Gather VPC info
      ec2_vpc_subnet_info:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: subnetinfo

    - name: Gather Security Group information
      ec2_group_info:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: sginfo

    - name: Store vpc subnet fact
      set_fact:
        mysubnet: "{{ subnetinfo.subnets|map(attribute='subnet_id') | join(',')}}"

    - name: Store Security Group fact
      set_fact:
        mysg: "{{ sginfo.security_groups|map(attribute='group_id')|list }}"
    
    - name: print mysubnet
      debug: 
        var: mysubnet

    - name: EC2 basic provisioning
      ec2_instance:
        instance_type: t2.micro
        #image_id: ami-0b0af3577fe5e3532
        image_id: ami-0ad8ecac8af5fc52b
        count: "{{ how_many | int }}"
        region: "{{ region }}"
        security_groups: "{{ mysg }}"
        vpc_subnet_id: "{{ mysubnet }}"
        #key_name: aap-mesh-ec2
        key_name: aap-mesh-ec2-eu
        network:
          assign_public_ip: yes
        state: present
        wait: yes
        tags:
          owner: Ben
          stack: "{{ which_env }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2