---

- name: change EC2 instance state of Lab enviornment 
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws
    - ansible.builtin
    - community.general

  vars_files: 
    - credentials.yml
  vars:
    #Your region
    region: us-east-1

  tasks:

    - name: gather running instance information
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        uptime: 1
        filters:
          "tag:stack": "{{ which_env }}"
          instance-state-name: [ "running" ]
      register: ec2_instance_facts

    - name: print fact
      debug:
        var: ec2_instance_facts


    #- name: Start my lab EC2 instances
    #  ec2_instance:
    #    region: "{{ region }}"
    #    aws_access_key: "{{ aws_access_key }}"
    #    aws_secret_key: "{{ aws_secret_key }}"
    #    filters:
    #      #stack: lab
    #      stack: "{{ which_env }}"
    #    state: running
    #  tags: start

    #- name: Stop my lab EC2 instances
    #  ec2_instance:
    #    region: "{{ region }}"
    #    aws_access_key: "{{ aws_access_key }}"
    #    aws_secret_key: "{{ aws_secret_key }}"
    #    state: stopped
    #    tags:
    #      stack: "{{ which_env }}"
    #  tags: stop
    - name: Stop my lab EC2 instances
      ec2_instance:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance_ids: "{{ item.instance_id }}"
        state: stopped
      loop: "{{ ec2_instance_facts.instances }}"
      tags: stop