---
- name: Create RHEL 8 EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws
    - ansible.builtin

  vars_files: 
    - credentials.yml
  vars:
    #Your region
    #region: us-east-1
    region: eu-west-2
    sgname: AA-Lab
  tasks:

    - name: Gather VPC info
      ec2_vpc_subnet_info:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: subnetinfo

    - name: Gather Security Group information
      ec2_group_info:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: sginfo

    
    - name: Store vpc subnet fact
      set_fact:
        mysubnet: "{{ subnetinfo.subnets|map(attribute='subnet_id') | join(',')}}"

    - name: Store Security Group fact
      set_fact:
        mysg: "{{ sginfo.security_groups|map(attribute='group_id')|list }}"

    - name: EC2 basic provisioning
      ec2:
        instance_type: t2.xlarge
        #us-east-1
        #image: ami-0b0af3577fe5e3532
        # eu-west-2 
        image: ami-0ad8ecac8af5fc52b
        count: 3
        region: "{{ region }}"
        group_id: "{{ mysg }}"
        vpc_subnet_id: "{{ mysubnet }}"
        #us-east-1
        #key_name: aap-mesh-ec2
        #EU-London
        key_name: aap-mesh-ec2-eu
        wait: yes
        #state: present
        instance_tags:
          owner: Ben
          stack: lab
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2

    - name: Create new volume using SSD storage
      ec2_vol:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        instance: "{{ item.id }}"
        volume_size: 100
        volume_type: gp2
      loop: "{{ ec2.instances }}"
      register: ec2_vol