---
- name: Create RHEL 8 EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws
    - ansible.builtin

  vars_files: 
    - credentials.yml
  vars:
    #Your region
    #region: us-east-1
    region: "{{ which_region }}" 
    #sgname: AA-Lab
    #sgname: "{{ which_security_group }}" 
  tasks:

    - name: gather running instance information
      ec2_instance_info:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        filters:
          "tag:stack": "{{ which_env }}"
      register: get_status
      tags: gather

    - name: Print facts
      debug:
        var: get_status
      tags: print_facts

    - name: Store Security Group fact
      set_fact:
        #mysg: "{{ sginfo.security_groups|map(attribute='group_id')|list }}"
        ec2_ip_addr: "{{ get_status.instances.network_interfaces|map(attribute='public_ip')|list }}"

    - name: Print facts
      debug:
        var: ec2_ip_addr
      tags: print_ip
    