---
- name: Create RHEL 8 EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws
    - ansible.builtin

  vars_files: 
    - credentials.yml
  vars:
    #Your region
    #region: us-east-1
    region: "{{ which_region }}" 
  tasks:

    - name: gather running instance information
      ec2_instance_info:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        filters:
          "tag:stack": "{{ which_env }}"
      register: get_status
      tags: gather

    - name: Print EC2 Information fori {{ which_env }}
      debug:
        var: get_status

    #- name: Store EC2 private IP address info 
    #  set_fact:
    #    ec2_ip: "{{ ec2_ip_private | default([]) + [ item ] }}"
    #  loop: "{{ get_status.instances | json_query('[*].public_ip_address') }}"
    
    - name: Update SNOW CMDB
      servicenow.itsm.configuration_item:
        state: "{{ status }}"
        name: "{{ item.private_dns_name }}"
        ip_address: "{{ item.private_ip_address | default(omit) }}"
        environment: test
        sys_class_name: cmdb_ci_server
        sys_id: "{{ sys_id | default(omit) }}"
        other:
          classification: Development
          u_region: "{{ item.placement.availability_zone }}"
      delegate_to: localhost
      loop: "{{ get_status.instances }}"