---

- name: change EC2 instance state of Lab enviornment v1 
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws
    - ansible.builtin
    - community.general

  vars_files: 
    - credentials.yml
  vars:
    #Your region
    region: us-east-1

  tasks:

    - name: gather running instance information
      ec2_instance_info:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        filters:
          "tag:stack": "{{ which_env }}"
      register: get_status
      tags: gather

    - name: Print facts
      debug:
        var: get_status

    - name: Start my lab EC2 instances
      ec2_instance:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance_ids: "{{ item.instance_id }}"
        instance_type: "{{ item.instance_type }}"
        vpc_subnet_id: "{{ item.subnet_id }}"
        state: running
      loop: "{{ get_status.instances }}"
      changed_when: True
      tags: start

    - name: Stop my lab EC2 instances
      ec2_instance:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance_ids: "{{ item.instance_id }}"
        instance_type: "{{ item.instance_type }}"
        vpc_subnet_id: "{{ item.subnet_id }}"
        state: stopped
      changed_when: True
      loop: "{{ get_status.instances }}"
      tags: stop