---

- name: Schedule to change EC2 instance 
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws
    - ansible.builtin
    - community.general
    - ansible.controller

  vars_files: 
    - credentials.yml
  vars:
    #Your region
    #region: us-east-1
    region: "{{ which_region }}"

  tasks:

    - name: Build the Schedule for Stopping EC2 instances for {{ which_env }} in the {{ region }} region
      schedule:
        name: Park EC2 instances for {{ which_env }} in the {{ region }} region
        state: present
        unified_job_template: EC2-Stop
        #rrule: "{{ query('ansible.controller.schedule_rrule', frequency, start_date=stop_date_time,timezone='GMT',every=repetition | int) }}"
        #Use with Surveys
        rrule: "{{ query('ansible.controller.schedule_rrule', frequency, start_date=stop_date_time,timezone='US/Eastern',every=repetition | int) }}"
        extra_data:
          region: "{{ region }}"
          which_env: "{{ which_env }}"
      tags: schedule_stop_ec2

    - name: Build the Schedule for Starting EC2 instances for {{ which_env }} in the {{ region }} region 
      schedule:
        name: Unpark EC2 instances for {{ which_env }}  in the {{ region }} region
        state: present
        unified_job_template: EC2-Start
        #rrule: "{{ query('ansible.controller.schedule_rrule', frequency, start_date=start_date_time,timezone='GMT',every=repetition | int) }}"
        #Use with surveys
        rrule: "{{ query('ansible.controller.schedule_rrule', frequency, start_date=start_date_time,timezone='US/Eastern',every=repetition | int) }}"
        extra_data:
          region: "{{ region }}"
          which_env: "{{ which_env }}"
      tags: schedule_start_ec2