---

- name: Create SNOW Change Record 
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws
    - ansible.builtin
    - servicenow.itsm

  vars_files: 
    - credentials.yml
  vars:
    #Your region
    #region: us-east-1
    region: "{{ which_region }}" 
  tasks:

    - name: gather running instance information
      ec2_instance_info:
        region: "{{ which_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        filters:
          "private-dns-name": "{{ enter_ci }}"
      register: get_status
      tags: gather

    - name: update Change tasks
      change_request_task:
        state: closed 
        close_code: "successful"
        close_notes: "closed"
        number: "{{ set_change_task.record.number }}" 
        other:
          u_ec2_public_ip_address: "{{ get_status.instances[0].public_ip_address }}"

    - name: update ServiceNow Change Request
      change_request:
        state: review
        number: "{{ request.record.number }}"
      delegate_to: localhost

    - name: update ServiceNow Change Request
      change_request:
        state: closed
        number: "{{ request.record.number }}"
        close_code: "successful"
        close_notes: "closed"
      delegate_to: localhost

    #- name: Send Approval e-mail
    #  community.general.mail:
    #    host: "{{ EMAIL_HOST }}"
    #    username: "{{ EMAIL_USERNAME }}"
    #    password: "{{ EMAIL_PASSWORD }}"
    #    port: "{{ EMAIL_PORT }}"
    #    subject: "Approval request for ServiceNow Change Request {{ request.record.number }}"
    #    body: "You have a new CR Approval request. Please click on this URL to approve: https://{{ lookup('env', 'SN_INSTANCE') }}.service-now.com/nav_to.do?uri=change_request.do?sysparm_query=number={{ request.record.number }}"
    #    from: tower@shadowman.dev
    #    to: "{{ to_email }}"
    #  delegate_to: localhost

    - name: Query SNOW CMDB
      servicenow.itsm.configuration_item_info:
        query:
          - name: = {{ enter_ci }}
      register: get_id

    - name: Update SNOW CMDB
      servicenow.itsm.configuration_item:
        ##name: "{{ enter_ci }}"
        sys_class_name: cmdb_ci_server
        sys_id: "{{ get_id.record.sys_id }}"
        ip_address: "{{  get_status.instances[0].public_ip_address }}"
      delegate_to: localhost