---

- name: Create SNOW Change Record 
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws
    - ansible.builtin
    - servicenow.itsm

  vars_files: 
    - credentials.yml
  vars:
    #Your region
    #region: us-east-1
    region: "{{ which_region }}" 
  tasks:

    - name: Create ServiceNow Change Request
      change_request:
        type: normal
        short_description: reboot ec2 
        priority: high
        risk: moderate
        impact: low
        assignment_group: "CAB Approval"
        state: assess
        other:
          cmdb_ci: "{{ enter_ci }}"

      register: request
      delegate_to: localhost

    - name: Pass along request information
      set_stats:
        data:
          request: "{{ request }}"
        per_host: false
      delegate_to: localhost

    #- name: Send Approval e-mail
    #  community.general.mail:
    #    host: "{{ EMAIL_HOST }}"
    #    username: "{{ EMAIL_USERNAME }}"
    #    password: "{{ EMAIL_PASSWORD }}"
    #    port: "{{ EMAIL_PORT }}"
    #    subject: "Approval request for ServiceNow Change Request {{ request.record.number }}"
    #    body: "You have a new CR Approval request. Please click on this URL to approve: https://{{ lookup('env', 'SN_INSTANCE') }}.service-now.com/nav_to.do?uri=change_request.do?sysparm_query=number={{ request.record.number }}"
    #    from: tower@shadowman.dev
    #    to: "{{ to_email }}"
    #  delegate_to: localhost

    - name: Wait for Change Request approval
      change_request_info:
        number: "{{ request.record.number }}"
      until: change_request_status.records[0].state == "scheduled"
      retries: 50
      delay: 10
      register: change_request_status
      delegate_to: localhost

    - name: Update to implement the change request in ServiceNow
      change_request:
        state: implement
        number: "{{ request.record.number }}"
        assignment_group: "CAB Approval"
      delegate_to: localhost
    
    - name: gather running instance information
      ec2_instance_info:
        region: "{{ which_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        filters:
          "private-dns-name": "{{ enter_ci }}"
      register: get_status
      tags: gather
    
    - name: Add Change tasks
      change_request_task:
        configuration_item: "{{ enter_ci }}"
        change_request_number: "{{ request.record.number }}"
        type: implementation
        state: in_progress
        assignment_group: "CAB Approval"
        short_description: Reboot EC2
        description: "Reboot EC2"
        other: 
          u_ec2_public_ip_address: "{{ get_status.instances[0].public_ip_address }}"
      register: new_change_task        
    
    - name: Pass along change task information
      set_stats:
        data:
          set_change_task: "{{ new_change_task }}"
        per_host: false
      delegate_to: localhost

