---
- name: "Change EC2 state to start in HCP Terraform"
  hosts: localhost
  collections:
    - hashicorp.terraform
  vars:
    operation: "start"  # default, but can be overridden
  tasks:
    - name: "Trigger a run in HCP Terraform with variable operation=start"
      run:
        workspace: "start-ben-lab"
        organization: "Shadowman"
        run_message: "start EC2 State"
        tf_token: "{{ hcpterraform_api_token }}"
        auto_apply: true
        poll: true
        poll_interval: 5
        poll_timeout: 300
      register: tf_run
      tags: start

    - name: "Trigger a run in HCP Terraform with variable operation=stop"
      run:
        workspace: "start-ben-lab"
        workspace_id: "ws-JSabWAPzsDbDnpm9"
        organization: "Shadowman"
        run_message: "Change EC2 State"
        auto_apply: true
        variables:
          key: "operation"
          value: "stop"
      register: tf_run
      tags: stop

    #- name: "Wait for the run to complete"
    #  terraform:
    #    workspace_id: "ws-JSabWAPzsDbDnpm9"
    #    run_id: "{{ tf_run.run_id }}"
    #    state: "applied"
    #  async: 1800   # Adjust the timeout as needed (in seconds)
    #  poll: 5       # Poll every 5 seconds